site_name: YukiSakamoto.github.io
remote_branch: master
google_analytics: ['UA-108145348-1', 'yukisakamoto.github.io']
pages:
- Home: index.md
- Profile: profile.md
- Publications: publications.md
- Contact: contact.md
- Misc:
  - Tiny Hartree-Fock program: hf.md
